### ISSUE TITLE
ManimCE gifs not showing in builded jupyter book 

### ISSUE THREAD

**Issue by mscharling** [ManimCommunity/manim#2416]
I'm pretty new to the Jupyter Notebook/Book universe, so I'm sorry if this question seems silly.

I know ManimCE already supports Jupyter, but somehow I have this issue with rendered gifs now showing in my builded jupyter book. When I open my build in Chrome I just get the message `<IPython.core.display.Image object>` where my gif should have been.

I've tried to dig into different posts but nothing really seems to work. The funny thing is when I open my .ipynb file in jupyter-notebook and run my code-snip there is no problem. The problem occurs when I build my Jupyter Book.

This is the following code I'm able to execute in jupyter-notebook but somehow not when building the Jupyter Book:

```
from manim import * 
%%manim -v WARNING  --progress_bar None -r 400,200 --format=gif --disable_caching HelloManim 

class HelloManim(Scene):
    def construct(self):
        self.camera.background_color = "#ece6e2"
        banner_large = ManimBanner(dark_theme=False).scale(0.7)
        self.play(banner_large.create())
        self.play(banner_large.expand())
```

Has anyone else tried this and knows why this issue occur?

### Steps to reproduce

1. Construct new Jupyter notebook-file
2. Paste the code provided into a new code cell
3. Execute the code cell (it's working, right?)
4. Now build a Jupyter book with this notebook file (does it work for you?)

**Comment by mscharling** [comment]
First I thought it was an issue with [jupyter-manim](https://github.com/krassowski/jupyter-manim)-extension, but I found out I was using the extension all wrong (😅), cf. [my issue in the jupyter-manim repository](https://github.com/krassowski/jupyter-manim/issues/33).

I need some of the features from ManimCE and since jupyter-manim uses ManimCairo I hope someone in this repo is able to help me sort this one out.

**Comment by Darylgolden** [comment]
I'm not sure what you're trying to do, ManimCE already has Jupyter support built in.

**Comment by Darylgolden** [comment]
![image](https://user-images.githubusercontent.com/9102529/147893883-d68ef01f-14ac-4613-b289-ecebcaedfe35.png)

Works for me. Does rendering normal mp4s work for you?

**Comment by mscharling** [comment]
@Darylgolden I am able to run it in jupyter-notebook but when I build my notebook-file into a jupyter book the gif doesn't show when I opens the html-document. If I render as mp4 there is no problem what so ever but I would really like to have my animations as gifs.

**Comment by kolibril13** [comment]
@mscharling : 
It is possible to add gifs into jupyter books at all?
Maybe you can try:
```py
import sys
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation

fig, ax = plt.subplots()
fig.set_tight_layout(True)

print('fig size: {0} DPI, size in inches {1}'.format(
    fig.get_dpi(), fig.get_size_inches()))

x = np.arange(0, 20, 0.1)
ax.scatter(x, x + np.random.normal(0, 3.0, len(x)))
line, = ax.plot(x, x - 5, 'r-', linewidth=2)

def update(i):
    label = 'timestep {0}'.format(i)
    line.set_ydata(x - 5 + i)
    ax.set_xlabel(label)
    return line, ax
anim = FuncAnimation(fig, update, frames=np.arange(0, 10), interval=200)
anim.save('line.gif', dpi=80)
from IPython.display import HTML
HTML('<img src="line.gif">')
```
 and then create a jupyter book from it.
Then we know if this is a manim related problem, or a jupyter book problem
Also, I found other ways to display gifs in jupyter here:
https://github.com/ipython/ipython/issues/10045
Maybe you can also try the `from IPython.display import Image` syntax.
I remember there was a similar issue when reopening images from widgets, that got solved here:
https://twitter.com/martinRenou/status/1440617060640247815
Good luck!

**Comment by mscharling** [comment]
@kolibril13 The code you provided worked both in jupyter-notebook and when building the jupyter book. However, the .gif was located in my bookname-folder and not in bookname/_build/html-folder. But, that have been an issue with the media-folder created from manim as well. So, after building the book I have to put the media folder into bookname/_build/html-folder.

I have yet not get `from IPython.display import Image`-syntax to work. 

Any other suggestions?😅

Btw. the code I provided is from your (@kolibril13) FlyingFrames-document (which is absolutely great, so thanks for that!)

**Comment by kolibril13** [comment]
Oh, that is great!
I think there is a quick and dirty workaround that you can try:
Take this %capture_png magic:
https://discourse.jupyter.org/t/cell-magic-to-save-image-output-as-a-png-file/11906/2
And try to make it work for gif (I am not sure if this is possible at all).
Then display your gif with the same `HTML('<img src="line.gif">')` line from my example above.
That should then give you the option to not crash the Jupyter notebook.
I've used this capture_png in a similar problem when I've built the mobject gallery, see here:
https://github.com/kolibril13/mobject-gallery/blob/main/01Mobjects_Basics.ipynb

**Comment by behackl** [comment]
#2442 has introduced a `media_embed` config option which can be used to fully embed the rendered output in the notebook and therefore resolve any sort of path issues. I think using this resolves the issue regarding Jupyter books.

In case someone tries and it still doesn't work the way it is supposed to, we can reopen this issue and investigate further.
